# Generated by Django 3.2.16 on 2023-04-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titles',
            new_name='title',
        ),
    ]
